version: '3'

services:

  postgres:
    image: "postgres:9.6.1"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "test"

  redis:
    container_name: redis_db
    image: redis
    ports:
      - 6379:6379
    command: redis-server --requirepass redis
